openapi: 3.1.0
info:
  title: Orders API
  description: Orders API documentation which describes REST API
  version: 1.0.0
tags:
  - name: Orders
    description: |
      tag description.
  - name: Products
    description: |
      tag description.
servers:
  - url: "http://localhost:8080/api"
paths:
  /products:
    post:
      description: Allows to create product.
      operationId: createProduct
      summary: createProduct
      tags:
        - Products
      responses:
        "200":
          $ref: "#/components/responses/SingleProductResponse"
    get:
      description: Allows to get all products.
      operationId: getProducts
      summary: getProducts
      tags:
        - Products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{productId}:
    get:
      parameters:
        - name: productId
          in: path
          schema:
            type: string
            description: Identyfikator produktu.
      description: Allows to get product by id.
      operationId: getProduct
      summary: getProduct
      tags:
        - Products
      responses:
        "200":
          $ref: "#/components/responses/SingleProductResponse"
        "404":
          description: There is no product with given id.
components:
  responses:
    SingleProductResponse:
      description: Products data.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
  schemas:
    Product:
      type: object
      properties:
        id:
          description: Id product
          type: string
        name:
          type: string
        price:
          type: number
